# Generated by Django 5.0.3 on 2024-04-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoasset',
            old_name='title',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='videoasset',
            old_name='video_file',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='videoasset',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='videoasset',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
